# Basics

In [1]:
%load_ext sql
%sql sqlite:///chinook.db

Connecting to 'sqlite:///chinook.db'

In [2]:
%%sql
SELECT Bytes
    FROM tracks
    ORDER BY Bytes DESC
    LIMIT 10

Running query in 'sqlite:///chinook.db'

+------------+
|   Bytes    |
+------------+
| 1059546140 |
| 1054423946 |
| 587051735  |
| 577829804  |
| 574325829  |
| 570152232  |
| 558872190  |
| 555244214  |
| 554509033  |
| 552893447  |
+------------+
Truncated to displaylimit of 10.

In [3]:
%%sql
SELECT *
    FROM tracks
    WHERE AlbumId = 1 AND Bytes > 200000

Running query in 'sqlite:///chinook.db'

+---------+-----------------------------------------+---------+-------------+---------+-------------------------------------------+--------------+----------+-----------+
| TrackId |                   Name                  | AlbumId | MediaTypeId | GenreId |                  Composer                 | Milliseconds |  Bytes   | UnitPrice |
+---------+-----------------------------------------+---------+-------------+---------+-------------------------------------------+--------------+----------+-----------+
|    1    | For Those About To Rock (We Salute You) |    1    |      1      |    1    | Angus Young, Malcolm Young, Brian Johnson |    343719    | 11170334 |    0.99   |
|    6    |          Put The Finger On You          |    1    |      1      |    1    | Angus Young, Malcolm Young, Brian Johnson |    205662    | 6713451  |    0.99   |
|    7    |             Let's Get It Up             |    1    |      1      |    1    | Angus Young, Malcolm Young, Brian Johnson |    233926    | 7636561  |    0.99   |
|    8    |             Inject The Venom            |    1    |      1      |    1    | Angus Young, Malcolm Young, Brian Johnson |    210834    | 6852860  |    0.99   |
|    9    |                Snowballed               |    1    |      1      |    1    | Angus Young, Malcolm Young, Brian Johnson |    203102    | 6599424  |    0.99   |
|    10   |                Evil Walks               |    1    |      1      |    1    | Angus Young, Malcolm Young, Brian Johnson |    263497    | 8611245  |    0.99   |
|    11   |                  C.O.D.                 |    1    |      1      |    1    | Angus Young, Malcolm Young, Brian Johnson |    199836    | 6566314  |    0.99   |
|    12   |            Breaking The Rules           |    1    |      1      |    1    | Angus Young, Malcolm Young, Brian Johnson |    263288    | 8596840  |    0.99   |
|    13   |         Night Of The Long Knives        |    1    |      1      |    1    | Angus Young, Malcolm Young, Brian Johnson |    205688    | 6706347  |    0.99   |
|    14   |                Spellbound               |    1    |      1      |    1    | Angus Young, Malcolm Young, Brian Johnson |    270863    | 8817038  |    0.99   |
+---------+-----------------------------------------+---------+-------------+---------+-------------------------------------------+--------------+----------+-----------+
Truncated to displaylimit of 10.

In [9]:
%%sql
SELECT * 
    FROM customers
    WHERE State = "FL" OR State = "WA" OR State = "CA"

Running query in 'sqlite:///chinook.db'

+------------+-----------+----------+-----------------------+---------------------------+---------------+-------+---------+------------+-------------------+-------------------+-------------------------+--------------+
| CustomerId | FirstName | LastName |        Company        |          Address          |      City     | State | Country | PostalCode |       Phone       |        Fax        |          Email          | SupportRepId |
+------------+-----------+----------+-----------------------+---------------------------+---------------+-------+---------+------------+-------------------+-------------------+-------------------------+--------------+
|     16     |   Frank   |  Harris  |      Google Inc.      | 1600 Amphitheatre Parkway | Mountain View |   CA  |   USA   | 94043-1351 | +1 (650) 253-0000 | +1 (650) 253-0000 |    fharris@google.com   |      4       |
|     17     |    Jack   |  Smith   | Microsoft Corporation |      1 Microsoft Way      |    Redmond    |   WA  |   USA   | 98052-8300 | +1 (425) 882-8080 | +1 (425) 882-8081 | jacksmith@microsoft.com |      5       |
|     19     |    Tim    |  Goyer   |       Apple Inc.      |      1 Infinite Loop      |   Cupertino   |   CA  |   USA   |   95014    | +1 (408) 996-1010 | +1 (408) 996-1011 |     tgoyer@apple.com    |      3       |
|     20     |    Dan    |  Miller  |          None         |    541 Del Medio Avenue   | Mountain View |   CA  |   USA   | 94040-111  | +1 (650) 644-3358 |        None       |   dmiller@comcast.com   |      4       |
|     22     |  Heather  | Leacock  |          None         |      120 S Orange Ave     |    Orlando    |   FL  |   USA   |   32801    | +1 (407) 999-7788 |        None       |    hleacock@gmail.com   |      4       |
+------------+-----------+----------+-----------------------+---------------------------+---------------+-------+---------+------------+-------------------+-------------------+-------------------------+--------------+

In [8]:
%%sql
SELECT * 
    FROM customers
    WHERE State IN ("FL","WA","CA")

Running query in 'sqlite:///chinook.db'

+------------+-----------+----------+-----------------------+---------------------------+---------------+-------+---------+------------+-------------------+-------------------+-------------------------+--------------+
| CustomerId | FirstName | LastName |        Company        |          Address          |      City     | State | Country | PostalCode |       Phone       |        Fax        |          Email          | SupportRepId |
+------------+-----------+----------+-----------------------+---------------------------+---------------+-------+---------+------------+-------------------+-------------------+-------------------------+--------------+
|     16     |   Frank   |  Harris  |      Google Inc.      | 1600 Amphitheatre Parkway | Mountain View |   CA  |   USA   | 94043-1351 | +1 (650) 253-0000 | +1 (650) 253-0000 |    fharris@google.com   |      4       |
|     17     |    Jack   |  Smith   | Microsoft Corporation |      1 Microsoft Way      |    Redmond    |   WA  |   USA   | 98052-8300 | +1 (425) 882-8080 | +1 (425) 882-8081 | jacksmith@microsoft.com |      5       |
|     19     |    Tim    |  Goyer   |       Apple Inc.      |      1 Infinite Loop      |   Cupertino   |   CA  |   USA   |   95014    | +1 (408) 996-1010 | +1 (408) 996-1011 |     tgoyer@apple.com    |      3       |
|     20     |    Dan    |  Miller  |          None         |    541 Del Medio Avenue   | Mountain View |   CA  |   USA   | 94040-111  | +1 (650) 644-3358 |        None       |   dmiller@comcast.com   |      4       |
|     22     |  Heather  | Leacock  |          None         |      120 S Orange Ave     |    Orlando    |   FL  |   USA   |   32801    | +1 (407) 999-7788 |        None       |    hleacock@gmail.com   |      4       |
+------------+-----------+----------+-----------------------+---------------------------+---------------+-------+---------+------------+-------------------+-------------------+-------------------------+--------------+

In [10]:
%%sql
SELECT InvoiceID, BillingAddress, Total
    FROM invoices
    WHERE Total BETWEEN 14.96 AND 18.86
    ORDER BY Total ASC

Running query in 'sqlite:///chinook.db'

+-----------+--------------------------------------+-------+
| InvoiceId |            BillingAddress            | Total |
+-----------+--------------------------------------+-------+
|    103    |        162 E Superior Street         | 15.86 |
|    208    |           Ullevålsveien 14           | 15.86 |
|    306    |            Klanova 9/506             | 16.86 |
|    313    |           68, Rue Jouvence           | 16.86 |
|     88    |           Calle Lira, 198            | 17.91 |
|     89    | Rotenturmstraße 4, 1010 Innere Stadt | 18.86 |
|    201    |        319 N. Frances Street         | 18.86 |
+-----------+--------------------------------------+-------+

In [11]:
%%sql
SELECT *
    FROM tracks
    WHERE Name LIKE "%Br_wn%"

Running query in 'sqlite:///chinook.db'

+---------+----------------------+---------+-------------+---------+-----------+--------------+---------+-----------+
| TrackId |         Name         | AlbumId | MediaTypeId | GenreId |  Composer | Milliseconds |  Bytes  | UnitPrice |
+---------+----------------------+---------+-------------+---------+-----------+--------------+---------+-----------+
|   1053  | Bad, Bad Leroy Brown |    83   |      1      |    12   | jim croce |    169900    | 5548581 |    0.99   |
|   1150  |    Mr. Brownstone    |    90   |      2      |    1    |    None   |    228924    | 3816323 |    0.99   |
+---------+----------------------+---------+-------------+---------+-----------+--------------+---------+-----------+

In [12]:
%%sql
SELECT FirstName, LastName, Phone
    FROM customers
    WHERE Phone IS NULL

Running query in 'sqlite:///chinook.db'

+-----------+----------+-------+
| FirstName | LastName | Phone |
+-----------+----------+-------+
|  Ladislav |  Kovács  |  None |
+-----------+----------+-------+

In [16]:
bs = %sql SELECT Bytes FROM tracks
bs=bs.DataFrame()
bs = bs["Bytes"].tolist()
bs[:10]

Running query in 'sqlite:///chinook.db'

[11170334,
 5510424,
 3990994,
 4331779,
 6290521,
 6713451,
 7636561,
 6852860,
 6599424,
 8611245]

In [20]:
import sqlalchemy as sa
import pandas as pd

In [26]:
engine = sa.create_engine("sqlite:///chinook.db")
query = "SELECT Milliseconds, Bytes FROM tracks"

conn = engine.raw_connection()
df = pd.read_sql(query, con=conn)

df.head()

C:\Users\qstef\AppData\Local\Temp\ipykernel_14804\1082777400.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, con=conn)

   Milliseconds     Bytes
0        343719  11170334
1        342562   5510424
2        230619   3990994
3        252051   4331779
4        375418   6290521

# Grouping

In [29]:
%%sql
SELECT AlbumId, COUNT(TrackId) AS TracksNum, ROUND(SUM(UnitPrice), 2) AS TotalPrice, ROUND(AVG(Milliseconds) / 1000.0, 0) AS MeanTrackSec
    FROM tracks
    GROUP BY AlbumId
    ORDER BY TotalPrice DESC
    LIMIT 10

Running query in 'sqlite:///chinook.db'

+---------+-----------+------------+--------------+
| AlbumId | TracksNum | TotalPrice | MeanTrackSec |
+---------+-----------+------------+--------------+
|   141   |     57    |   56.43    |    264.0     |
|   229   |     26    |   51.74    |    2718.0    |
|   230   |     25    |   49.75    |    2594.0    |
|   251   |     25    |   49.75    |    1533.0    |
|   231   |     24    |   47.76    |    2637.0    |
|   253   |     24    |   47.76    |    2926.0    |
|   228   |     23    |   45.77    |    2599.0    |
|   250   |     22    |   43.78    |    1302.0    |
|   227   |     19    |   37.81    |    2778.0    |
|   261   |     17    |   33.83    |    2322.0    |
+---------+-----------+------------+--------------+
Truncated to displaylimit of 10.

In [35]:
engine = sa.create_engine("sqlite:///chinook.db")
query = "SELECT * FROM tracks"

conn = engine.raw_connection()
try:
    df_tracks = pd.read_sql(query, con=conn)
finally:
    conn.close()

df_sum = df_tracks.groupby('AlbumId').agg(TracksNum=('TrackId', 'count'), TotalPrice=('UnitPrice', 'sum'), MeanTrackSec=('Milliseconds', 'mean')).reset_index()

df_sum['MeanTrackSec'] = (df_sum['MeanTrackSec'] / 1000).round(0)
df_sum['TotalPrice'] = df_sum['TotalPrice'].round(2)
df_sum = df_sum.sort_values(by='TotalPrice', ascending=False).head(10)

df_sum

C:\Users\qstef\AppData\Local\Temp\ipykernel_14804\3625311577.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_tracks = pd.read_sql(query, con=conn)

     AlbumId  TracksNum  TotalPrice  MeanTrackSec
140      141         57       56.43         264.0
228      229         26       51.74        2718.0
229      230         25       49.75        2594.0
250      251         25       49.75        1533.0
230      231         24       47.76        2637.0
252      253         24       47.76        2926.0
227      228         23       45.77        2599.0
249      250         22       43.78        1302.0
226      227         19       37.81        2778.0
260      261         17       33.83        2322.0

In [39]:
%%sql
SELECT AlbumId, COUNT(TrackId) AS TrackCount
    FROM tracks
    GROUP BY AlbumId
    HAVING TrackCount BETWEEN 18 AND 20
    LIMIT 5

Running query in 'sqlite:///chinook.db'

+---------+------------+
| AlbumId | TrackCount |
+---------+------------+
|    21   |     18     |
|    37   |     20     |
|    54   |     20     |
|    55   |     20     |
|    72   |     18     |
+---------+------------+

In [40]:
%%sql
SELECT AlbumId, GROUP_CONCAT(Name, "; ") AS Tracks
    FROM tracks
    GROUP BY AlbumId
    LIMIT 5

Running query in 'sqlite:///chinook.db'

+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| AlbumId |                                                                                                         Tracks                                                                                                        |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|    1    |              For Those About To Rock (We Salute You); Put The Finger On You; Let's Get It Up; Inject The Venom; Snowballed; Evil Walks; C.O.D.; Breaking The Rules; Night Of The Long Knives; Spellbound              |
|    2    |                                                                                                   Balls to the Wall                                                                                                   |
|    3    |                                                                                Fast As a Shark; Restless and Wild; Princess of the Dawn                                                                               |
|    4    |                                           Go Down; Dog Eat Dog; Let There Be Rock; Bad Boy Boogie; Problem Child; Overdose; Hell Ain't A Bad Place To Be; Whole Lotta Rosie                                           |
|    5    | Walk On Water; Love In An Elevator; Rag Doll; What It Takes; Dude (Looks Like A Lady); Janie's Got A Gun; Cryin'; Amazing; Blind Man; Deuces Are Wild; The Other Side; Crazy; Eat The Rich; Angel; Livin' On The Edge |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+